const processes={
  recebimento:{module:'Estoque',title:'Recebimento de materiais',icon:'📦',description:'Fluxo de preparação, recebimento, conferência e disponibilização de materiais para produção.',version:'1.0',updated:'24/07/2026',about:'Processo completo desde a preparação da estrutura do estoque até a disponibilização do material para utilização na produção, mantendo rastreabilidade e integridade das informações.',steps:[
    {n:1,title:'Cadastrar almoxarifado',text:'Definição do almoxarifado e sua finalidade operacional.',type:'orange',objective:'Cadastrar os almoxarifados utilizados pela empresa.',rules:['Descrição única','Apenas almoxarifados ativos podem operar','Tipo definido conforme finalidade','Grupo de usuários associado'],module:'Estoque',attention:'A configuração completa atualmente depende de outras funcionalidades; há oportunidade de centralização.'},
    {n:2,title:'Estrutura física',text:'Configuração de locais de armazenagem e endereços.',type:'orange',objective:'Organizar a estrutura física necessária para localização e rastreabilidade.',rules:['Local vinculado ao almoxarifado','Endereço único no local','Somente locais ativos recebem movimentações'],module:'Estoque'},
    {n:3,title:'Cadastro de materiais',text:'Cadastro, classificação e identificação dos materiais.',type:'orange',objective:'Cadastrar os itens que serão movimentados no estoque.',rules:['Item vinculado a subgrupo','Código único','Item ativo para operação'],module:'Estoque'},
    {n:4,title:'Configurações',text:'Regras, parâmetros e controles operacionais.',type:'orange',objective:'Definir as características e controles aplicáveis ao armazenamento.',rules:['Controle de acesso','Refrigeração','Quarentena','Umidade','Refugo'],module:'Estoque'},
    {n:5,title:'Inspeção (se aplicável)',text:'Validação do veículo e condições da entrega.',type:'blue',objective:'Verificar se a inspeção veicular é necessária e, quando exigida, registrar sua aprovação.',rules:['Inspeção antes do recebimento','Somente inspeções aprovadas prosseguem','Registro para rastreabilidade'],module:'Estoque'},
    {n:6,title:'Aprovação (se aplicável)',text:'Liberação prévia para recebimento do material.',type:'blue',objective:'Verificar se existe exigência de aprovação antes do recebimento.',rules:['Exigência definida por parametrização','Quando exigida, aprovação é obrigatória','Sem exigência, segue para recebimento'],module:'Estoque'},
    {n:7,title:'Recebimento',text:'Registro físico da entrega no almoxarifado.',type:'blue',objective:'Registrar formalmente a entrada física dos materiais entregues pelo fornecedor.',rules:['Pré-requisitos atendidos','Dados de transporte registrados','Vínculo com fornecedor e documentos'],module:'Estoque'},
    {n:8,title:'Conferência',text:'Verificação física e documental do material.',type:'blue',objective:'Validar se os materiais entregues estão em conformidade com a documentação e as condições físicas observadas.',rules:['Quantidade recebida','Número do lote','Data de validade','Integridade das embalagens','Identificação do material','Documentação fiscal'],module:'Estoque',attention:'O tratamento de divergências não foi totalmente demonstrado e deve ser validado na homologação.'},
    {n:9,title:'Entrada no Estoque',text:'Registro oficial da incorporação do material.',type:'green',objective:'Formalizar a incorporação do material ao estoque.',rules:['Conferência concluída','Material aprovado','Vínculo com recebimento preservado'],module:'Estoque'},
    {n:10,title:'Endereçamento',text:'Definição do local físico de armazenamento.',type:'green',objective:'Direcionar o material para endereço compatível com sua configuração.',rules:['Endereço previamente cadastrado','Pertence ao almoxarifado','Respeita parâmetros do local'],module:'Estoque'},
    {n:11,title:'Disponibilização',text:'Material disponível para utilização nas etapas seguintes.',type:'green',objective:'Concluir a etapa logística do recebimento.',rules:['Localização registrada','Material rastreável','Apto para etapas subsequentes'],module:'Estoque'}
  ]},
  quarentena:{module:'Estoque + CQ',title:'Quarentena de materiais e produtos',icon:'🧪',description:'Fluxo integrado de quarentena, amostragem, análise, liberação e movimentação do material aprovado.',version:'1.0',updated:'13/08/2026',about:'O processo inicia na parametrização do item, passa pela entrada em quarentena e atravessa Estoque e Controle da Qualidade até o laudo liberado e a movimentação do material aprovado.',steps:[
    {n:1,title:'Parametrizar item',text:'Definir quarentena e controles de análise.',type:'orange',objective:'Determinar se o item será submetido à quarentena e quais análises serão aplicáveis.',rules:['Controle de quarentena','Análise físico-química','Análise microbiológica','Controles de lote e validade'],module:'Estoque'},
    {n:2,title:'Entrada em quarentena',text:'Material direcionado ao endereço de quarentena.',type:'orange',objective:'Registrar a entrada e bloquear o item para uso até a avaliação.',rules:['Entrada registrada','Endereço de quarentena','Lote e validade quando aplicáveis'],module:'Estoque'},
    {n:3,title:'Solicitação de análise',text:'Geração automática conforme parametrização.',type:'blue',objective:'Iniciar o processo de Controle da Qualidade a partir do item em quarentena.',rules:['Gerada automaticamente','Pode ser físico-química, microbiológica ou ambas','Relacionada ao item/lote'],module:'Controle da Qualidade',automatic:true},
    {n:4,title:'Programar amostragem',text:'Definir coleta, data e responsável.',type:'blue',objective:'Planejar a coleta da amostra conforme a regra configurada.',rules:['Item e lote identificados','Tipo de análise','Data de coleta','Responsável'],module:'Controle da Qualidade'},
    {n:5,title:'Pesagem e separação',text:'Estoque retira e prepara a amostra.',type:'orange',objective:'Retirar, pesar e separar a quantidade necessária para análise.',rules:['Quantidade requisitada','Peso bruto, tara e líquido quando aplicáveis','Balança e identificação','Amostra disponibilizada ao CQ'],module:'Estoque'},
    {n:6,title:'Programar análise',text:'Planejar execução e responsável.',type:'blue',objective:'Preparar a solicitação para execução da análise.',rules:['Solicitação existente','Data prevista','Responsável','Amostra disponível'],module:'Controle da Qualidade'},
    {n:7,title:'Executar análise',text:'Registrar resultados e evidências.',type:'blue',objective:'Executar a análise e registrar os resultados conforme a regra de avaliação.',rules:['Regra de análise','Resultado','Justificativas','Observações','Anexos'],module:'Controle da Qualidade'},
    {n:8,title:'Emitir laudo',text:'Revisão, aprovação e liberação.',type:'green',objective:'Aprovar a análise e disponibilizar o laudo liberado.',rules:['Análise executada','Revisor habilitado','Validade do laudo','Etiqueta de aprovação'],module:'Controle da Qualidade'},
    {n:9,title:'Movimentar aprovado',text:'Retirar da quarentena e armazenar.',type:'green',objective:'Transferir o material aprovado para seu endereço de armazenamento.',rules:['Laudo liberado','Resultado APROVADO','Origem e destino definidos','Quantidade confirmada'],module:'Estoque'}
  ]}
};

let current='recebimento';let dark=false;
const app=document.getElementById('app');
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function renderProcess(key=current){current=key;const p=processes[key];document.getElementById('crumb-module').textContent=p.module;document.getElementById('crumb-process').textContent=p.title;
 app.innerHTML=`<div class="hero"><div><h1><span class="emoji">${p.icon}</span> ${esc(p.title)}</h1><p>${esc(p.description)}</p><div class="tags"><span class="tag orange">Módulo: ${esc(p.module)}</span><span class="tag">Versão: ${p.version}</span><span class="tag">Última atualização: ${p.updated}</span></div></div><button class="primary-btn" id="overviewBtn">☷ Visão geral do fluxo</button></div>
 <div class="flow-card"><div class="phasebar"><div class="phase one"><strong>1. Preparação</strong><small>Estrutura e configuração</small></div><div class="phase two"><strong>2. Execução</strong><small>Atividades e controles</small></div><div class="phase three"><strong>3. Resultado</strong><small>Conclusão e disponibilização</small></div></div><div class="flow-area"><div class="flow-grid">${p.steps.map((s,i)=>stepHTML(s,i)).join('')}</div></div></div>
 <div class="below"><div class="info-tabs"><div class="tabs"><button class="tab active" data-tab="people">♙ Quem executa</button><button class="tab" data-tab="inputs">◇ Entradas</button><button class="tab" data-tab="outputs">□ Saídas</button><button class="tab" data-tab="systems">▦ Sistemas</button><button class="tab" data-tab="indicators">⌁ Indicadores</button></div><div class="tab-body" id="tabBody">${tabContent('people',p)}</div></div><div class="right-stack"><div class="side-card"><h3>ⓘ Sobre este processo</h3><p>${esc(p.about)}</p><span class="more" id="aboutBtn">Ver objetivo e escopo completos →</span></div><div class="side-card"><h3>▣ Informações do fluxo</h3><div class="mini-meta"><div><b>Módulo</b>${esc(p.module)}</div><div><b>Áreas envolvidas</b>Estoque • Controle da Qualidade</div><div><b>Documentação</b>Especificação funcional por fluxo</div><div><b>Base de trabalho</b>Processo operacional documentado</div></div></div>${attentionCard(p)}</div></div>`;
 document.querySelectorAll('.step').forEach(el=>el.onclick=()=>openStep(Number(el.dataset.index)));
 document.getElementById('overviewBtn').onclick=()=>openOverview(p);document.getElementById('aboutBtn').onclick=()=>openOverview(p);
 document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById('tabBody').innerHTML=tabContent(t.dataset.tab,p)});
}
function stepHTML(s,i){return `<div class="step ${s.type}" data-index="${i}"><div class="step-num">${s.n}</div><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p>${s.automatic?'<span class="auto">⚡ automático</span>':''}</div>`}
function attentionCard(p){const a=p.steps.find(s=>s.attention);return a?`<div class="side-card attention"><h3>⚠ Ponto de atenção</h3><p>${esc(a.attention)}</p><span class="more" onclick="openStep(${p.steps.indexOf(a)})">Saiba mais →</span></div>`:''}