(function(){
  const baseRenderJourney=window.renderJourney;if(typeof baseRenderJourney!=='function')return;
  const stage={name:'Fábrica',question:'Onde o medicamento será produzido?',intro:'A etapa de Fábrica representa a estrutura física e operacional onde ocorrerão as atividades relacionadas à produção. Nessa etapa são organizados os almoxarifados, a estrutura de quarentena, equipamentos, instrumentos, centros de trabalho e localizações que compõem a estrutura fabril. Essa organização estabelece os recursos e os locais utilizados nas etapas posteriores do processo produtivo. Ao final, a estrutura da fábrica está definida para suportar a produção.',items:[
    {name:'Almoxarifados',meaning:'Representam as áreas destinadas à organização e armazenamento dos materiais utilizados na operação.',example:'Cadastro dos almoxarifados utilizados pela fábrica e identificação de sua finalidade.',objective:'Estabelecer a base para organização das áreas de estoque e dos materiais.'},
    {name:'Quarentena',meaning:'Representa a condição/local de armazenagem destinada aos materiais que aguardam avaliação antes de sua disponibilização.',example:'Um material recebido pode permanecer em Quarentena até que as avaliações previstas sejam concluídas.',objective:'Manter controlados os materiais que ainda não estão disponíveis para utilização.'},
    {name:'Equipamentos',meaning:'Representam os equipamentos utilizados nas atividades da operação.',example:'Cadastro de um equipamento e vinculação ao ambiente correspondente.',objective:'Identificar os equipamentos disponíveis para utilização nos processos.'},
    {name:'Instrumentos',meaning:'Representam os instrumentos utilizados para medição e controle.',example:'Cadastro de um instrumento e sua associação ao equipamento ou ambiente, quando aplicável.',objective:'Manter os instrumentos identificados e rastreáveis.'},
    {name:'Centro de Trabalhos',meaning:'Representa uma estrutura utilizada para organizar a execução das atividades produtivas.',example:'Cadastro dos centros de trabalho e definição das atividades e responsáveis relacionados.',objective:'Organizar a execução das atividades produtivas.'},
    {name:'Localizações',meaning:'Representam os locais e endereçamentos utilizados para vincular recursos e áreas dentro da estrutura da fábrica.',example:'Vincular recursos e locais à estrutura da fábrica e consolidar seus endereçamentos.',objective:'Manter a estrutura física organizada e integrada.'}
  ];
  function card(item){return `<article class="stage1-detail-card"><h2>${item.name}</h2><div class="stage1-detail-content"><div class="stage1-content-block"><strong>O QUE SIGNIFICA?</strong><p>${item.meaning}</p></div><div class="stage1-content-block"><strong>EXEMPLO</strong><p>${item.example}</p></div><div class="stage1-content-block"><strong>OBJETIVO</strong><p>${item.objective}</p></div></div></article>`}
  window.renderJourney=function(index=0,selected=-1){if(index!==1){baseRenderJourney(index,selected);return}const s=stage;journeyIndex=1;const sel=(Number.isInteger(selected)&&selected>=0&&selected<s.items.length)?selected:-1;journeySelected=sel;closeGeneralFlow();document.body.classList.remove('home-mode','journey-intro-mode');document.body.classList.add('journey-mode','journey-stage1-mode');setCrumbs('Jornada','Fábrica');document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));const initial=sel<0;const content=initial?`<article class="stage1-detail-card"><h2>Fábrica</h2><div class="stage1-detail-content"><p>${s.intro}</p></div></article>`:card(s.items[sel]);app.innerHTML=`<section class="stage1-screen"><header class="stage1-header"><div class="stage1-header-context"><button class="stage1-brand" onclick="renderHome()"><img src="assets/ilabpharma-logo.svg" alt="iLabPharma"></button><div class="stage1-page-title"><strong>${s.question.replace('?', ' <em>?</em>')}</strong><span>A estrutura física e operacional precisa estar definida antes que os recursos sejam utilizados na produção.</span></div></div><div class="stage1-actions"><button class="stage1-home-btn" onclick="renderHome()">⌂</button></div></header><div class="stage1-layout"><aside class="stage1-sidebar"><div class="stage1-side-title"><button type="button" class="stage1-side-title-button" onclick="renderJourney(1,-1)"><span>02</span><div><strong>Fábrica</strong><small>${s.question}</small></div></button></div><nav class="stage1-items">${s.items.map((x,i)=>`<button class="stage1-item ${i===sel?'selected':''}" onclick="renderJourney(1,${i})"><span>${String(i+1).padStart(2,'0')}</span><strong>${x.name}</strong></button>`).join('')}<button class="stage1-item stage1-flow-item" onclick="renderStage2FlowList()"><span>◎</span><strong>Fluxo</strong><em>›</em></button></nav><div class="stage1-side-result"><span>AO FINAL DESTA ETAPA</span><strong>A fábrica estará<br>estruturada para<br>a produção.</strong></div></aside><main class="stage1-main"><div class="stage1-questions"><span class="stage1-section-label">AS PERGUNTAS QUE ESTRUTURAM ESTA ETAPA</span><div class="stage1-question-grid"><button onclick="renderJourney(1,0)"><b>01</b><strong>Onde os materiais são armazenados?</strong><span>Almoxarifados e Quarentena</span></button><button onclick="renderJourney(1,2)"><b>02</b><strong>Quais recursos fazem parte da estrutura?</strong><span>Equipamentos e instrumentos</span></button><button onclick="renderJourney(1,5)"><b>03</b><strong>Como a estrutura física é organizada?</strong><span>Centro de trabalhos e localizações</span></button></div></div>${content}<div class="stage1-bottom"><button class="ghost-btn" onclick="renderJourney(0)">← Voltar</button><div><span>Você está aqui</span><strong>Fábrica</strong></div><button class="primary-btn" onclick="renderJourney(2)">Continuar →</button></div></main></div></section>`};
})();